
#define iMOAB_Initialize                     imoab_initialize_
#define iMOAB_InitializeFortran              imoab_initializefortran_
#define iMOAB_Finalize                       imoab_finalize_
#define iMOAB_RegisterApplication            imoab_registerapplication_
#define iMOAB_RegisterFortranApplication     imoab_registerfortranapplication_
#define iMOAB_DeregisterApplication          imoab_deregisterapplication_
#define iMOAB_ReadHeaderInfo                 imoab_readheaderinfo_
#define iMOAB_LoadMesh                       imoab_loadmesh_
#define iMOAB_WriteMesh                      imoab_writemesh_
#define iMOAB_GetMeshInfo                    imoab_getmeshinfo_
#define iMOAB_GetVertexID                    imoab_getvertexid_
#define iMOAB_GetVertexOwnership             imoab_getvertexownership_
#define iMOAB_GetVisibleVerticesCoordinates  imoab_getvisibleverticescoordinates_
#define iMOAB_GetBlockID                     imoab_getblockid_
#define iMOAB_GetBlockInfo                   imoab_getblockinfo_
#define iMOAB_GetVisibleElementsInfo         imoab_getvisibleelementsinfo_
#define iMOAB_GetBlockElementConnectivities  imoab_getblockelementconnectivities_
#define iMOAB_GetElementConnectivity         imoab_getelementconnectivity_
#define iMOAB_GetElementOwnership            imoab_getelementownership_
#define iMOAB_GetElementID                   imoab_getelementid_
#define iMOAB_GetPointerToSurfaceBC          imoab_getpointertosurfacebc_
#define iMOAB_GetPointerToVertexBC           imoab_getpointertovertexbc_
#define iMOAB_DefineTagStorage               imoab_definetagstorage_
#define iMOAB_SetIntTagStorage               imoab_setinttagstorage_
#define iMOAB_GetIntTagStorage               imoab_getinttagstorage_
#define iMOAB_SetDoubleTagStorage            imoab_setdoubletagstorage_
#define iMOAB_GetDoubleTagStorage            imoab_getdoubletagstorage_
#define iMOAB_SynchronizeTags                imoab_synchronizetags_
#define iMOAB_GetNeighborElements            imoab_getneighborelements_
#define iMOAB_GetNeighborVertices            imoab_getneighborvertices_
